"""Controlled natural drawing cadence for Image Draw Bot v1.0.4.

Human Mode deliberately does *not* add coordinate jitter.  The geometry generated by
Precision/PortraitPlanner remains exact; only stroke direction, small local ordering,
and timing cadence are varied.  This keeps portrait detail reproducible and prevents a
"natural" preset from silently reducing drawing accuracy.
"""
from __future__ import annotations

import hashlib
import math
import random
from dataclasses import dataclass
from typing import Iterable, Sequence

HUMAN_MODES = ("Off", "Subtle", "Natural", "Strong")

_PROFILES = {
    "Off": dict(window=1, reverse=0.0, pace_jitter=0.0, endpoint_slow=0.0,
                pause_every=(0, 0), pause_range=(0.0, 0.0)),
    "Subtle": dict(window=3, reverse=0.18, pace_jitter=0.05, endpoint_slow=0.08,
                   pause_every=(24, 38), pause_range=(0.018, 0.045)),
    "Natural": dict(window=5, reverse=0.32, pace_jitter=0.10, endpoint_slow=0.14,
                    pause_every=(16, 29), pause_range=(0.028, 0.075)),
    "Strong": dict(window=7, reverse=0.45, pace_jitter=0.16, endpoint_slow=0.22,
                   pause_every=(10, 20), pause_range=(0.045, 0.120)),
}


def validate_human_mode(value: str) -> str:
    if value not in HUMAN_MODES:
        raise ValueError("Choose a valid Human Mode.")
    return value


def profile(value: str) -> dict:
    return dict(_PROFILES[validate_human_mode(value)])


def stable_seed(groups: Sequence[Sequence[tuple[int, int, int, int]]], mode: str) -> int:
    """Return a deterministic seed without storing image contents or file metadata."""
    validate_human_mode(mode)
    h = hashlib.blake2s(digest_size=8)
    h.update(mode.encode("utf-8"))
    h.update(str(len(groups)).encode("ascii"))
    for group in groups:
        h.update(str(len(group)).encode("ascii"))
        # A few geometry samples are enough to keep different plans distinct.
        for stroke in list(group[:4]) + list(group[-4:]):
            h.update((",".join(map(str, stroke)) + ";").encode("ascii"))
    return int.from_bytes(h.digest(), "little")


def _undirected(stroke: tuple[int, int, int, int]):
    x1, y1, x2, y2 = stroke
    a, b = (x1, y1), (x2, y2)
    return (a, b) if a <= b else (b, a)


def humanize_strokes(strokes: Sequence[tuple[int, int, int, int]], mode: str,
                     seed: int) -> list[tuple[int, int, int, int]]:
    """Vary only direction and local ordering; never change stroke geometry."""
    cfg = profile(mode)
    if mode == "Off" or len(strokes) < 2:
        return list(strokes)
    rng = random.Random(int(seed))
    window = int(cfg["window"])
    result: list[tuple[int, int, int, int]] = []
    for start in range(0, len(strokes), window):
        chunk = list(strokes[start:start + window])
        # Keep changes local so structure-prioritized portrait strokes still arrive early.
        if len(chunk) > 1:
            rng.shuffle(chunk)
        for x1, y1, x2, y2 in chunk:
            if (x1, y1) != (x2, y2) and rng.random() < cfg["reverse"]:
                result.append((x2, y2, x1, y1))
            else:
                result.append((x1, y1, x2, y2))
    return result


@dataclass
class HumanCadence:
    mode: str
    seed: int

    def __post_init__(self):
        self.mode = validate_human_mode(self.mode)
        self.cfg = profile(self.mode)
        self.rng = random.Random(int(self.seed) ^ 0x48554D414E)
        lo, hi = self.cfg["pause_every"]
        self.next_pause = self.rng.randint(lo, hi) if hi else 0

    def movement_delay(self, base_delay: float, step_index: int, step_count: int) -> float:
        """Small cadence variation with gentle ease-in/ease-out, never coordinate jitter."""
        base = max(0.0, float(base_delay))
        if self.mode == "Off" or base == 0.0:
            return base
        n = max(1, int(step_count))
        p = max(0.0, min(1.0, step_index / max(1, n - 1)))
        # Slower near stroke ends, slightly faster around the middle. Average stays near base.
        endpoint = abs(2.0 * p - 1.0) - 0.5
        factor = 1.0 + self.cfg["endpoint_slow"] * endpoint
        factor += self.rng.uniform(-self.cfg["pace_jitter"], self.cfg["pace_jitter"])
        return base * max(0.55, min(1.55, factor))

    def boundary_pause(self, completed_strokes: int) -> float:
        if self.mode == "Off" or not self.next_pause:
            return 0.0
        if completed_strokes < self.next_pause:
            return 0.0
        low, high = self.cfg["pause_range"]
        pause = self.rng.uniform(low, high)
        lo, hi = self.cfg["pause_every"]
        self.next_pause = completed_strokes + self.rng.randint(lo, hi)
        return pause


def human_overhead_seconds(stroke_count: int, mode: str) -> float:
    """Conservative ETA overhead for the short boundary pauses."""
    cfg = profile(mode)
    count = max(0, int(stroke_count))
    lo, hi = cfg["pause_every"]
    if mode == "Off" or hi <= 0 or count <= 0:
        return 0.0
    avg_every = (lo + hi) / 2.0
    p0, p1 = cfg["pause_range"]
    return (count / avg_every) * ((p0 + p1) / 2.0)
