"""Speed profiles and bounded stroke ordering for Draw Studio v1.0.5.

The optimizer is intentionally geometry-preserving.  It may reorder nearby strokes
and reverse a line, but it never changes the set of undirected segments generated by
the renderer.  Reordering is bounded in small windows so structure-prioritized
portrait plans still draw important detail early.
"""
from __future__ import annotations

import math
from collections import Counter
from typing import Iterable, Sequence

SPEED_PROFILES = {
    'Safe': {
        'base_delay': 0.010,
        'path_wait_factor': 1.00,
        'travel_wait_factor': 0.65,
        'boundary_wait_factor': 0.80,
        'travel_window': 8,
        'progress_every': 20,
    },
    'Balanced': {
        'base_delay': 0.006,
        'path_wait_factor': 0.60,
        'travel_wait_factor': 0.30,
        'boundary_wait_factor': 0.45,
        'travel_window': 28,
        'progress_every': 40,
    },
    'Fast': {
        'base_delay': 0.003,
        'path_wait_factor': 0.35,
        'travel_wait_factor': 0.15,
        'boundary_wait_factor': 0.25,
        'travel_window': 64,
        'progress_every': 80,
    },
}

LEGACY_SPEED_NAMES = {
    'Careful': 'Safe',
    'Normal': 'Balanced',
    'Försiktig': 'Safe',
    'Snabb': 'Fast',
}


def normalize_speed(value: str) -> str:
    value = LEGACY_SPEED_NAMES.get(value, value)
    if value not in SPEED_PROFILES:
        raise ValueError('Choose a valid drawing speed.')
    return value


def profile(value: str) -> dict:
    return dict(SPEED_PROFILES[normalize_speed(value)])


def base_delay(value: str) -> float:
    return float(profile(value)['base_delay'])


def phase_delay(base: float, speed: str, phase: str) -> float:
    """Return the wait used after a movement phase.

    UI-control settling remains outside this helper on purpose; only drawing motion
    is accelerated.  This prevents a fast profile from making Paint palette/tool
    clicks less reliable.
    """
    cfg = profile(speed)
    factors = {
        'path': cfg['path_wait_factor'],
        'travel': cfg['travel_wait_factor'],
        'boundary': cfg['boundary_wait_factor'],
    }
    if phase not in factors:
        raise ValueError('Unknown speed phase.')
    return max(0.0005, max(0.0, float(base)) * float(factors[phase]))


def _distance(a, b) -> float:
    return math.hypot(float(a[0]) - float(b[0]), float(a[1]) - float(b[1]))


def _reverse(stroke):
    x1, y1, x2, y2 = stroke
    return (x2, y2, x1, y1)


def _undirected(stroke):
    x1, y1, x2, y2 = stroke
    a, b = (x1, y1), (x2, y2)
    return (a, b) if a <= b else (b, a)


def travel_distance(strokes: Sequence[tuple[int, int, int, int]]) -> float:
    """Pen-up distance between consecutive strokes (not stroke length itself)."""
    total = 0.0
    previous = None
    for x1, y1, x2, y2 in strokes:
        if previous is not None:
            total += _distance(previous, (x1, y1))
        previous = (x2, y2)
    return total


def optimize_strokes(strokes: Sequence[tuple[int, int, int, int]], speed: str,
                     allow_reverse: bool = True) -> list[tuple[int, int, int, int]]:
    """Reduce pen-up travel inside bounded windows while preserving geometry.

    The first stroke of each window remains the anchor.  This stops the optimizer
    from pulling low-priority portrait shading in front of high-priority facial
    structure merely because it is geographically closer.
    """
    cfg = profile(speed)
    if len(strokes) < 3:
        return list(strokes)
    window = max(1, int(cfg['travel_window']))
    result = []
    previous_end = None

    for start in range(0, len(strokes), window):
        chunk = list(strokes[start:start + window])
        if not chunk:
            continue

        # Keep the first item as the priority anchor, but choose its direction to
        # connect efficiently to the previous window when geometry allows it.
        first = chunk.pop(0)
        if allow_reverse and previous_end is not None and first[:2] != first[2:]:
            if _distance(previous_end, first[2:]) < _distance(previous_end, first[:2]):
                first = _reverse(first)
        result.append(first)
        current = first[2:]

        while chunk:
            best_index = 0
            best_reverse = False
            best_cost = float('inf')
            for index, stroke in enumerate(chunk):
                start_point, end_point = stroke[:2], stroke[2:]
                cost = _distance(current, start_point)
                reverse_cost = _distance(current, end_point) if allow_reverse and start_point != end_point else float('inf')
                if reverse_cost < cost:
                    cost, reverse = reverse_cost, True
                else:
                    reverse = False
                # Stable tie-breaker keeps output deterministic.
                if cost < best_cost - 1e-9:
                    best_index, best_reverse, best_cost = index, reverse, cost
            chosen = chunk.pop(best_index)
            if best_reverse:
                chosen = _reverse(chosen)
            result.append(chosen)
            current = chosen[2:]
        previous_end = current

    return result


def estimated_motion_seconds(path_moves: int, stroke_count: int, dot_count: int,
                             base: float, speed: str) -> float:
    """Estimate drawing-motion waits using the same phase factors as execution."""
    path_moves = max(0, int(path_moves))
    stroke_count = max(0, int(stroke_count))
    dot_count = max(0, int(dot_count))
    return (
        path_moves * phase_delay(base, speed, 'path') +
        stroke_count * phase_delay(base, speed, 'travel') +
        stroke_count * phase_delay(base, speed, 'boundary') +
        dot_count * 0.015
    )
