APP_NAME = 'Image Draw Bot'
APP_TAGLINE = 'Automatic Image Drawing'
APP_VERSION = '1.0.144-rc1'
FILE_VERSION = '1.0.144'
BUILD_CHANNEL = 'rc'
LEGACY_APP_NAME = 'Draw Studio'
EXECUTABLE_NAME = 'ImageDrawBot.exe'
LEGACY_EXECUTABLE_NAME = 'DrawStudio.exe'
